"""Provide small validated objects reused by unit and integration tests.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- function source_spec: line 31
- function checksum: line 46
- function make_block: line 52
- function make_document: line 83
- function repository_root: line 103
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

from pathlib import Path
from typing import cast

import pytest

from docfoundry.models import (
    BlockKind,
    Checksum,
    ExtractedBlock,
    SourceDocument,
    SourceLocation,
    SourceSpec,
)


@pytest.fixture
def source_spec() -> SourceSpec:
    """Return a minimal approved synthetic source declaration."""

    return SourceSpec(
        source_id="fixture-source",
        revision="1.0",
        product_model="Fixture Model",
        owner="Test Suite",
        license="MIT synthetic fixture",
        path="sources/fixture.pdf",
        migration_status="approved",
    )


@pytest.fixture
def checksum() -> Checksum:
    """Return a schema-valid deterministic test checksum."""

    return cast(Checksum, "a" * 64)


def make_block(
    index: int,
    kind: BlockKind,
    text: str = "",
    *,
    heading_level: int | None = None,
    table_rows: tuple[tuple[str, ...], ...] = (),
) -> ExtractedBlock:
    """Build a source-located block for normalization and validation tests.

    Args:
        index: One-based stable block sequence.
        kind: Extracted semantic kind.
        text: Visible source text.
        heading_level: Optional semantic heading rank.
        table_rows: Optional tabular cell matrix.

    Returns:
        A validated extracted block on source page one.
    """

    return ExtractedBlock(
        block_id=f"fixture-source.p1.b{index}",
        kind=kind,
        text=text,
        location=SourceLocation(page=1, bbox=(0.0, float(index), 100.0, float(index + 1))),
        heading_level=heading_level,
        table_rows=table_rows,
    )


def make_document(
    source_spec: SourceSpec,
    checksum: Checksum,
    blocks: tuple[ExtractedBlock, ...],
) -> SourceDocument:
    """Build a one-page source document for deterministic unit tests.

    Args:
        source_spec: Fixture source metadata.
        checksum: Fixture source digest.
        blocks: Ordered extraction results.

    Returns:
        A validated source document.
    """

    return SourceDocument(source=source_spec, checksum=checksum, page_count=1, blocks=blocks)


@pytest.fixture
def repository_root() -> Path:
    """Return the repository root independent of the current directory."""

    return Path(__file__).resolve().parents[1]
