"""Measure a documented local performance bound for the synthetic corpus.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- function test_eight_document_build_completes_within_budget: line 20
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

import time
from pathlib import Path

import pytest

from docfoundry.pipeline import PipelineConfig, run_pipeline


@pytest.mark.performance
def test_eight_document_build_completes_within_budget(
    tmp_path: Path, repository_root: Path
) -> None:
    """Complete the small reference corpus within a generous CI-safe budget."""

    started = time.perf_counter()
    report = run_pipeline(
        PipelineConfig(
            repository_root / "examples" / "source-registry.yaml",
            tmp_path / "performance-build",
        )
    )
    elapsed = time.perf_counter() - started
    assert report.source_count == 8
    assert elapsed < 20.0
