"""Test bounded PDF extraction with valid and hostile fixture inputs.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- function test_extracts_text_table_and_provenance: line 21
- function test_rejects_oversized_and_malformed_inputs: line 36
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

from pathlib import Path

import pytest

from docfoundry.extractor import ExtractionError, ExtractorConfig, PdfExtractor
from docfoundry.models import BlockKind, SourceSpec
from docfoundry.registry import compute_sha256


def test_extracts_text_table_and_provenance(repository_root: Path, source_spec: SourceSpec) -> None:
    """Extract ordered headings, warnings, paragraphs, and ruled table rows."""

    path = repository_root / "examples" / "sources" / "pump-controller-guide.pdf"
    document = PdfExtractor().extract(path, source_spec, compute_sha256(path))

    kinds = {block.kind for block in document.blocks}
    assert document.page_count == 2
    assert {BlockKind.HEADING, BlockKind.WARNING, BlockKind.TABLE} <= kinds
    assert all(block.location.page >= 1 for block in document.blocks)
    assert any(
        block.table_rows[0][0] == "Parameter" for block in document.blocks if block.table_rows
    )


def test_rejects_oversized_and_malformed_inputs(
    repository_root: Path, source_spec: SourceSpec
) -> None:
    """Fail predictably on resource-limit and parser violations."""

    valid = repository_root / "examples" / "sources" / "pump-controller-guide.pdf"
    with pytest.raises(ExtractionError, match="byte limit"):
        PdfExtractor(ExtractorConfig(max_file_bytes=1)).extract(
            valid, source_spec, compute_sha256(valid)
        )
    with pytest.raises(ExtractionError, match="page limit"):
        PdfExtractor(ExtractorConfig(max_pages=1)).extract(
            valid, source_spec, compute_sha256(valid)
        )

    malformed = repository_root / "tests" / "fixtures" / "malformed.pdf"
    with pytest.raises(ExtractionError, match="unable to parse"):
        PdfExtractor().extract(malformed, source_spec, compute_sha256(malformed))
