"""Test quality gates, deterministic reports, and escaped semantic HTML.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- function _complete_topic: line 34
- function test_valid_topic_writes_reports_trace_and_escaped_html: line 58
- function test_validation_flags_images_tables_and_duplicate_ids: line 79
- function test_blocked_report_cannot_be_published: line 100
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from conftest import make_block, make_document

from docfoundry.models import (
    BlockKind,
    Checksum,
    IssueSeverity,
    MigrationIssue,
    SourceSpec,
    Topic,
)
from docfoundry.normalizer import normalize_document
from docfoundry.publisher import publish_site, topic_filename
from docfoundry.reporting import build_report, write_canonical_data, write_report
from docfoundry.validator import publication_is_allowed, validate_topics


def _complete_topic(source_spec: SourceSpec, checksum: Checksum) -> tuple[Topic, object]:
    """Build a topic containing escaped prose, a warning, and a semantic table."""

    blocks = (
        make_block(1, BlockKind.HEADING, "API reference", heading_level=1),
        make_block(2, BlockKind.PARAGRAPH, "Use <script>alert('no')</script> safely."),
        make_block(
            3,
            BlockKind.WARNING,
            "NOTICE: condition=retry occurs; consequence=duplicate work; "
            "avoidance=use an idempotency key",
        ),
        make_block(
            4,
            BlockKind.TABLE,
            table_rows=(("Method", "Result"), ("GET", "Status")),
        ),
    )
    document = make_document(source_spec, checksum, blocks)
    topics, issues = normalize_document(document)
    assert not issues
    return topics[0], document


def test_valid_topic_writes_reports_trace_and_escaped_html(
    tmp_path: Path, source_spec: SourceSpec, checksum: Checksum
) -> None:
    """Publish accessible table markup while escaping untrusted source text."""

    topic, document = _complete_topic(source_spec, checksum)
    report = build_report((document,), (topic,), ())  # type: ignore[arg-type]
    write_report(report, tmp_path)
    write_canonical_data((topic,), tmp_path)
    publish_site((topic,), report, tmp_path)

    html = (tmp_path / "site" / "topics" / topic_filename(topic)).read_text(encoding="utf-8")
    assert "&lt;script&gt;" in html
    assert '<th scope="col">Method</th>' in html
    assert '<aside class="warning"' in html
    assert (tmp_path / "site" / "reports" / "migration-report.html").is_file()
    trace = (tmp_path / "canonical" / "trace.jsonl").read_text(encoding="utf-8")
    assert json.loads(trace.splitlines()[0])["source_block_id"] == topic.blocks[0].source_block_id
    assert (tmp_path / "reports" / "migration-report.md").is_file()


def test_validation_flags_images_tables_and_duplicate_ids(
    source_spec: SourceSpec, checksum: Checksum
) -> None:
    """Find image review, missing headers, irregular rows, and duplicate topic IDs."""

    blocks = (
        make_block(1, BlockKind.IMAGE, "Image requires review."),
        make_block(2, BlockKind.TABLE, table_rows=(("", ""), ("one",))),
    )
    topics, _ = normalize_document(make_document(source_spec, checksum, blocks))
    issues = validate_topics((topics[0], topics[0]))
    codes = {issue.code for issue in issues}
    assert {
        "topic.duplicate-id",
        "image.alt-required",
        "table.header-missing",
        "table.irregular",
    } <= codes
    assert publication_is_allowed(issues) is False


def test_blocked_report_cannot_be_published(
    tmp_path: Path, source_spec: SourceSpec, checksum: Checksum
) -> None:
    """Refuse to render HTML when the report contains an error finding."""

    topic, document = _complete_topic(source_spec, checksum)
    issue = MigrationIssue(
        code="test.blocking",
        severity=IssueSeverity.ERROR,
        message="Synthetic blocking issue.",
        source_id=source_spec.source_id,
    )
    report = build_report((document,), (topic,), (issue,))  # type: ignore[arg-type]
    assert not report.publication_allowed
    with pytest.raises(ValueError, match="blocked"):
        publish_site((topic,), report, tmp_path)
