"""Enforce documentation, source-header, workflow, and neutrality policies.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- variable PINNED_ACTION: line 20
- variable FORBIDDEN_REFERENCES: line 21
- function _text_files: line 27
- function test_repository_is_employer_neutral_and_documented: line 42
- function test_python_files_have_indexed_headers_and_symbol_docstrings: line 60
- function test_workflows_are_pinned_and_least_privilege: line 84
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

import ast
import re
from pathlib import Path

PINNED_ACTION = re.compile(r"uses:\s+[\w-]+/[\w-]+@[0-9a-f]{40}(?:\s|$)")
FORBIDDEN_REFERENCES = (
    "".join(("op", "to", " ", "2", "2")),
    "".join(("op", "to", "2", "2")),
)


def _text_files(root: Path) -> tuple[Path, ...]:
    """Return repository text files while excluding generated and Git data."""

    suffixes = {".md", ".py", ".toml", ".yaml", ".yml", ".json", ".txt", ".css", ".html"}
    return tuple(
        path
        for path in root.rglob("*")
        if path.is_file()
        and path.suffix.lower() in suffixes
        and ".git" not in path.parts
        and ".venv" not in path.parts
        and "build" not in path.parts
    )


def test_repository_is_employer_neutral_and_documented(repository_root: Path) -> None:
    """Keep prohibited employer references out and require core documentation."""

    combined = "\n".join(
        path.read_text(encoding="utf-8", errors="ignore") for path in _text_files(repository_root)
    ).casefold()
    assert not any(reference in combined for reference in FORBIDDEN_REFERENCES)
    for relative in (
        "README.md",
        "CONTRIBUTING.md",
        "SECURITY.md",
        "docs/architecture.md",
        "docs/testing-and-validation.md",
        "docs/file-reference.md",
    ):
        assert (repository_root / relative).is_file(), relative


def test_python_files_have_indexed_headers_and_symbol_docstrings(repository_root: Path) -> None:
    """Require module headers, resolved indexes, and function/class documentation."""

    python_files = tuple(
        sorted(
            path
            for directory in ("src", "tests", "tools")
            for path in (repository_root / directory).rglob("*.py")
        )
    )
    for path in python_files:
        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source)
        assert ast.get_docstring(tree), path
        assert "@@SYMBOL_INDEX_START" in source and "@@SYMBOL_INDEX_END" in source
        assert any(
            marker in source
            for marker in ("- function ", "- class ", "- variable ", "- no top-level symbols")
        )
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                assert ast.get_docstring(node), f"{path}:{node.lineno} {node.name}"


def test_workflows_are_pinned_and_least_privilege(repository_root: Path) -> None:
    """Require immutable action pins and read-only default permissions."""

    workflows = tuple((repository_root / ".github" / "workflows").glob("*.yml"))
    assert workflows
    for workflow in workflows:
        text = workflow.read_text(encoding="utf-8")
        assert "permissions:\n  contents: read" in text
        uses_lines = [
            line.strip() for line in text.splitlines() if line.strip().startswith("uses:")
        ]
        assert uses_lines
        assert all(PINNED_ACTION.search(line) for line in uses_lines)
