"""Test complete successful, blocked, repeatable, and CLI pipeline runs.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- function _artifact_bytes: line 24
- function test_example_pipeline_is_byte_repeatable: line 34
- function test_failed_source_commits_reports_but_not_site: line 50
- function test_output_policy_and_cli_codes: line 82
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import pytest

from docfoundry.cli import main
from docfoundry.pipeline import PipelineConfig, PublicationBlocked, run_pipeline


def _artifact_bytes(directory: Path) -> dict[str, bytes]:
    """Read every build artifact into a relative-path mapping."""

    return {
        path.relative_to(directory).as_posix(): path.read_bytes()
        for path in directory.rglob("*")
        if path.is_file()
    }


def test_example_pipeline_is_byte_repeatable(tmp_path: Path, repository_root: Path) -> None:
    """Produce byte-identical artifacts from the complete eight-document corpus."""

    registry = repository_root / "examples" / "source-registry.yaml"
    first = tmp_path / "first"
    second = tmp_path / "second"
    first_report = run_pipeline(PipelineConfig(registry, first))
    second_report = run_pipeline(PipelineConfig(registry, second))

    assert first_report == second_report
    assert first_report.source_count == 8
    assert first_report.topic_count >= 16
    assert _artifact_bytes(first) == _artifact_bytes(second)
    assert (first / "site" / "index.html").is_file()


def test_failed_source_commits_reports_but_not_site(tmp_path: Path, repository_root: Path) -> None:
    """Preserve review evidence and withhold the site for a malformed PDF."""

    shutil.copy(repository_root / "tests" / "fixtures" / "malformed.pdf", tmp_path / "bad.pdf")
    registry = tmp_path / "registry.json"
    registry.write_text(
        json.dumps(
            {
                "registry_version": 1,
                "sources": [
                    {
                        "source_id": "malformed-source",
                        "revision": "1",
                        "product_model": "Broken Fixture",
                        "owner": "Tests",
                        "license": "MIT",
                        "path": "bad.pdf",
                    }
                ],
            }
        ),
        encoding="utf-8",
    )
    output = tmp_path / "blocked"
    with pytest.raises(PublicationBlocked) as blocked:
        run_pipeline(PipelineConfig(registry, output))

    assert blocked.value.report.issue_counts["error"] == 1
    assert (output / "PUBLICATION_BLOCKED.txt").is_file()
    assert not (output / "site").exists()


def test_output_policy_and_cli_codes(tmp_path: Path, repository_root: Path) -> None:
    """Protect existing output and expose stable success and error exit codes."""

    registry = repository_root / "examples" / "source-registry.yaml"
    output = tmp_path / "build"
    assert main(["build", str(registry), "--output", str(output)]) == 0
    assert main(["build", str(registry), "--output", str(output)]) == 1
    assert main(["build", str(registry), "--output", str(output), "--overwrite"]) == 0
    unrelated = tmp_path / "unrelated"
    unrelated.mkdir()
    (unrelated / "keep.txt").write_text("not a generated build", encoding="utf-8")
    assert main(["build", str(registry), "--output", str(unrelated), "--overwrite"]) == 1
    assert (unrelated / "keep.txt").is_file()
    with pytest.raises(ValueError, match="dedicated"):
        run_pipeline(PipelineConfig(registry, Path.cwd()))
