"""Test registry parsing, filesystem containment, hashing, and checksums.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- function _payload: line 33
- function test_load_json_and_hash_source: line 52
- function test_yaml_and_unsupported_extension: line 69
- function test_source_spec_rejects_unsafe_paths: line 88
- function test_resolver_rejects_missing_wrong_type_and_symlink_escape: line 95
- function test_checksum_validation_and_chunk_size: line 116
- function test_registry_rejects_duplicate_ids: line 130
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from pydantic import ValidationError

from docfoundry.models import SourceRegistry, SourceSpec
from docfoundry.registry import (
    RegistryError,
    compute_sha256,
    load_registry,
    resolve_source_path,
    verify_checksum,
)


def _payload(path: str = "source.pdf") -> dict[str, object]:
    """Return a valid raw registry payload using the selected source path."""

    return {
        "registry_version": 1,
        "sources": [
            {
                "source_id": "source-one",
                "revision": "1.0",
                "product_model": "Model One",
                "owner": "Docs",
                "license": "MIT",
                "path": path,
                "migration_status": "approved",
            }
        ],
    }


def test_load_json_and_hash_source(tmp_path: Path) -> None:
    """Load JSON, resolve its PDF, and calculate a known digest."""

    source_path = tmp_path / "source.pdf"
    source_path.write_bytes(b"source bytes")
    registry_path = tmp_path / "registry.json"
    registry_path.write_text(json.dumps(_payload()), encoding="utf-8")

    registry = load_registry(registry_path)
    resolved = resolve_source_path(registry_path, registry.sources[0])

    assert resolved == source_path
    assert compute_sha256(source_path) == (
        "4d4823794cbed3c4ee0bbc684c8f66e1dfd5afa6f078d494ce254ec5a4671753"
    )


def test_yaml_and_unsupported_extension(tmp_path: Path) -> None:
    """Accept YAML while rejecting unrecognized registry extensions."""

    yaml_path = tmp_path / "registry.yaml"
    yaml_path.write_text(
        "registry_version: 1\nsources:\n"
        "  - source_id: source-one\n    revision: '1'\n    product_model: Model\n"
        "    owner: Docs\n    license: MIT\n    path: source.pdf\n",
        encoding="utf-8",
    )
    assert load_registry(yaml_path).sources[0].source_id == "source-one"

    text_path = tmp_path / "registry.txt"
    text_path.write_text("not a registry", encoding="utf-8")
    with pytest.raises(RegistryError, match="must use"):
        load_registry(text_path)


@pytest.mark.parametrize("path", ["../secret.pdf", "/absolute.pdf", "C:/absolute.pdf"])
def test_source_spec_rejects_unsafe_paths(path: str) -> None:
    """Reject absolute and parent-traversal registry paths."""

    with pytest.raises(ValidationError):
        SourceSpec.model_validate(_payload(path)["sources"][0])  # type: ignore[index]


def test_resolver_rejects_missing_wrong_type_and_symlink_escape(tmp_path: Path) -> None:
    """Reject absent, non-PDF, and escaping symlink targets."""

    registry_path = tmp_path / "registry.json"
    registry_path.write_text("{}", encoding="utf-8")
    source = SourceSpec.model_validate(_payload()["sources"][0])  # type: ignore[index]
    with pytest.raises(RegistryError, match="does not exist"):
        resolve_source_path(registry_path, source)

    wrong_type = tmp_path / "source.pdf"
    wrong_type.mkdir()
    with pytest.raises(RegistryError, match="does not exist"):
        resolve_source_path(registry_path, source)

    wrong_type.rmdir()
    (tmp_path / "source.txt").write_text("text", encoding="utf-8")
    text_source = source.model_copy(update={"path": "source.txt"})
    with pytest.raises(RegistryError, match="unsupported"):
        resolve_source_path(registry_path, text_source)


def test_checksum_validation_and_chunk_size(tmp_path: Path, source_spec: SourceSpec) -> None:
    """Enforce declared digests and positive bounded read sizes."""

    source_path = tmp_path / "file.pdf"
    source_path.write_bytes(b"abc")
    actual = compute_sha256(source_path, chunk_size=1)
    verify_checksum(source_spec, actual)
    mismatched = source_spec.model_copy(update={"sha256": "0" * 64})
    with pytest.raises(RegistryError, match="checksum mismatch"):
        verify_checksum(mismatched, actual)
    with pytest.raises(ValueError, match="positive"):
        compute_sha256(source_path, chunk_size=0)


def test_registry_rejects_duplicate_ids(source_spec: SourceSpec) -> None:
    """Reject repeated identifiers that would make provenance ambiguous."""

    with pytest.raises(ValidationError, match="unique"):
        SourceRegistry(registry_version=1, sources=[source_spec, source_spec])
