"""Test topic segmentation, classification, warning parsing, and slug safety.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- function test_slugify_always_returns_a_bounded_ascii_slug: line 24
- function test_complete_warning_and_task_heading_are_structured: line 35
- function test_incomplete_warning_blocks_publication: line 57
- function test_heading_jump_duplicate_titles_and_content_types: line 68
- function test_empty_document_is_reported: line 88
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

from conftest import make_block, make_document
from hypothesis import given
from hypothesis import strategies as st

from docfoundry.models import BlockKind, Checksum, ContentType, SourceSpec
from docfoundry.normalizer import normalize_document, slugify


@given(st.text())
def test_slugify_always_returns_a_bounded_ascii_slug(value: str) -> None:
    """Keep arbitrary Unicode titles within the identifier grammar."""

    result = slugify(value)
    assert result
    assert len(result) <= 40
    assert all(
        character.islower() or character.isdigit() or character == "-" for character in result
    )


def test_complete_warning_and_task_heading_are_structured(
    source_spec: SourceSpec, checksum: Checksum
) -> None:
    """Parse every safety field and classify an explicit procedure as a task."""

    blocks = (
        make_block(1, BlockKind.HEADING, "Installation procedure", heading_level=1),
        make_block(
            2,
            BlockKind.WARNING,
            "WARNING: condition=power is on; consequence=shock; avoidance=disconnect power",
        ),
    )
    topics, issues = normalize_document(make_document(source_spec, checksum, blocks))

    assert not issues
    assert topics[0].content_type is ContentType.TASK
    warning = topics[0].blocks[1].warning
    assert warning is not None
    assert warning.avoidance == "disconnect power"


def test_incomplete_warning_blocks_publication(source_spec: SourceSpec, checksum: Checksum) -> None:
    """Record absent safety fields as an error without inventing content."""

    block = make_block(1, BlockKind.WARNING, "CAUTION: condition=surface is hot")
    topics, issues = normalize_document(make_document(source_spec, checksum, (block,)))

    assert topics[0].blocks[0].warning is None
    assert issues[0].code == "warning.incomplete"
    assert "avoidance" in issues[0].message


def test_heading_jump_duplicate_titles_and_content_types(
    source_spec: SourceSpec, checksum: Checksum
) -> None:
    """Report rank jumps, suffix duplicate slugs, and infer stable topic types."""

    blocks = (
        make_block(1, BlockKind.HEADING, "Overview", heading_level=1),
        make_block(2, BlockKind.HEADING, "Deep heading", heading_level=3),
        make_block(3, BlockKind.HEADING, "Overview", heading_level=1),
        make_block(4, BlockKind.PARAGRAPH, "Reference material."),
        make_block(5, BlockKind.HEADING, "Fault diagnostics", heading_level=1),
    )
    topics, issues = normalize_document(make_document(source_spec, checksum, blocks))

    assert any(issue.code == "heading.rank-jump" for issue in issues)
    assert topics[0].topic_id.endswith(".overview")
    assert topics[1].topic_id.endswith(".overview-2")
    assert topics[2].content_type is ContentType.TROUBLESHOOTING


def test_empty_document_is_reported(source_spec: SourceSpec, checksum: Checksum) -> None:
    """Return a blocking no-content issue for an empty extraction."""

    topics, issues = normalize_document(make_document(source_spec, checksum, ()))

    assert not topics
    assert issues[0].code == "source.no-content"
