"""Public package interface for the documentation migration pipeline.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- variable __all__: line 13
- variable __version__: line 14
@@SYMBOL_INDEX_END
"""

from docfoundry.models import MigrationReport
from docfoundry.pipeline import PipelineConfig, run_pipeline

__all__ = ["MigrationReport", "PipelineConfig", "run_pipeline"]
__version__ = "0.1.0"
