"""Run the documentation foundry with ``python -m docfoundry``.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- no top-level symbols
@@SYMBOL_INDEX_END
"""

from docfoundry.cli import entrypoint

if __name__ == "__main__":
    entrypoint()
