"""Provide the command-line interface for reproducible documentation builds.

The CLI uses explicit exit codes: zero for success, two for blocked publication,
and one for invalid configuration or unexpected operational failure.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- function build_parser: line 24
- function main: line 47
- function entrypoint: line 80
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

import argparse
from collections.abc import Sequence
from pathlib import Path

from docfoundry.pipeline import PipelineConfig, PublicationBlocked, run_pipeline
from docfoundry.registry import RegistryError


def build_parser() -> argparse.ArgumentParser:
    """Create the argument parser without reading process-global state.

    Returns:
        Configured parser for the ``build`` command.
    """

    parser = argparse.ArgumentParser(
        prog="docfoundry",
        description="Build validated, provenance-linked HTML from registered PDFs.",
    )
    subcommands = parser.add_subparsers(dest="command", required=True)
    build = subcommands.add_parser("build", help="run the documentation pipeline")
    build.add_argument("registry", type=Path, help="YAML or JSON source registry")
    build.add_argument("--output", type=Path, required=True, help="dedicated build directory")
    build.add_argument(
        "--overwrite",
        action="store_true",
        help="replace the exact output directory when it already exists",
    )
    return parser


def main(arguments: Sequence[str] | None = None) -> int:
    """Run the requested command and return a process exit code.

    Args:
        arguments: Optional testable argument sequence; defaults to ``sys.argv``.

    Returns:
        Zero for success, two for a controlled publication block, or one on error.
    """

    parser = build_parser()
    namespace = parser.parse_args(arguments)
    try:
        report = run_pipeline(
            PipelineConfig(
                registry_path=namespace.registry,
                output_directory=namespace.output,
                overwrite=namespace.overwrite,
            )
        )
    except PublicationBlocked as error:
        print(f"BLOCKED: {error}")
        return 2
    except (FileExistsError, OSError, RegistryError, ValueError) as error:
        print(f"ERROR: {error}")
        return 1
    print(
        f"Published {report.topic_count} topics from {report.source_count} sources "
        f"as {report.build_id}."
    )
    return 0


def entrypoint() -> None:
    """Exit the installed console script with the CLI result."""

    raise SystemExit(main())
