"""Extract ordered PDF blocks with bounded resources and source coordinates.

The extractor uses layout dictionaries for text and image locations and table
detection for grid data. It does not execute PDF actions or embedded content.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- variable WARNING_PREFIX: line 42
- class ExtractionError: line 45
- function _as_bbox: line 49
- class ExtractorConfig: line 69
- function _median_font_size: line 85
- function _block_text: line 106
- function _classify_text: line 130
- function _inside_table: line 156
- class PdfExtractor: line 182
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

import math
import re
import statistics
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pymupdf

from docfoundry.models import (
    BlockKind,
    BoundingBox,
    Checksum,
    ExtractedBlock,
    SourceDocument,
    SourceLocation,
    SourceSpec,
)

WARNING_PREFIX = re.compile(r"^(DANGER|WARNING|CAUTION|NOTICE)\b", re.IGNORECASE)


class ExtractionError(RuntimeError):
    """Report a PDF parsing failure or a configured resource-limit breach."""


def _as_bbox(values: Iterable[float]) -> BoundingBox:
    """Convert a PDF rectangle into the fixed-width provenance contract.

    Args:
        values: Numeric PDF rectangle coordinates.

    Returns:
        Four floating-point coordinates.

    Raises:
        ValueError: If the parser provides a rectangle with another width.
    """

    coordinates = tuple(float(value) for value in values)
    if len(coordinates) != 4:
        raise ValueError(f"expected four bounding-box coordinates, got {len(coordinates)}")
    return coordinates


@dataclass(frozen=True, slots=True)
class ExtractorConfig:
    """Bound CPU- and memory-relevant work accepted by the PDF extractor.

    Attributes:
        max_file_bytes: Largest accepted source file.
        max_pages: Largest accepted page count.
        max_blocks_per_page: Largest accepted text/image block count per page.
        heading_ratio: Font-size ratio above the page median used for headings.
    """

    max_file_bytes: int = 25 * 1024 * 1024
    max_pages: int = 500
    max_blocks_per_page: int = 5_000
    heading_ratio: float = 1.25


def _median_font_size(blocks: Iterable[dict[str, Any]]) -> float:
    """Return the median positive text-span size, or a readable default.

    Args:
        blocks: PyMuPDF dictionary blocks for one page.

    Returns:
        Median font size in PDF points, defaulting to 10.0 when no text exists.

    Complexity:
        O(s log s) time and O(s) memory for s text spans.
    """

    sizes: list[float] = []
    for block in blocks:
        for line in block.get("lines", []):
            sizes.extend(float(span.get("size", 0.0)) for span in line.get("spans", []))
    positive_sizes = [size for size in sizes if size > 0 and math.isfinite(size)]
    return statistics.median(positive_sizes) if positive_sizes else 10.0


def _block_text(block: dict[str, Any]) -> tuple[str, float]:
    """Flatten text spans while preserving line boundaries and maximum size.

    Args:
        block: One PyMuPDF dictionary block.

    Returns:
        A normalized text string and the largest observed font size.

    Complexity:
        O(c) time and space for c extracted characters.
    """

    lines: list[str] = []
    max_size = 0.0
    for line in block.get("lines", []):
        spans = line.get("spans", [])
        line_text = "".join(str(span.get("text", "")) for span in spans).strip()
        max_size = max(max_size, *(float(span.get("size", 0.0)) for span in spans), 0.0)
        if line_text:
            lines.append(line_text)
    return "\n".join(lines).strip(), max_size


def _classify_text(
    text: str, font_size: float, median_size: float, ratio: float
) -> tuple[BlockKind, int | None]:
    """Classify a text block using visible labels and conservative typography.

    Args:
        text: Normalized block text.
        font_size: Largest font in the block.
        median_size: Median font size on the page.
        ratio: Minimum relative size for a heading candidate.

    Returns:
        Block kind and optional semantic heading level.

    Complexity:
        O(c) time for c characters in the first-line checks.
    """

    if WARNING_PREFIX.match(text):
        return BlockKind.WARNING, None
    is_short = len(text) <= 160 and text.count("\n") <= 1
    if is_short and font_size >= median_size * ratio:
        return BlockKind.HEADING, 1 if font_size >= median_size * 1.65 else 2
    return BlockKind.PARAGRAPH, None


def _inside_table(block_bbox: BoundingBox, table_bboxes: Sequence[BoundingBox]) -> bool:
    """Return whether most of a text block lies inside a detected table.

    Args:
        block_bbox: Text-block rectangle.
        table_bboxes: Table rectangles on the same page.

    Returns:
        True when at least 80 percent of the text rectangle overlaps a table.

    Complexity:
        O(t) time for t tables and O(1) extra memory.
    """

    x0, y0, x1, y1 = block_bbox
    area = max(0.0, x1 - x0) * max(0.0, y1 - y0)
    if area == 0:
        return False
    for table_bbox in table_bboxes:
        tx0, ty0, tx1, ty1 = table_bbox
        overlap = max(0.0, min(x1, tx1) - max(x0, tx0)) * max(0.0, min(y1, ty1) - max(y0, ty0))
        if overlap / area >= 0.8:
            return True
    return False


class PdfExtractor:
    """Convert one trusted-path PDF into typed blocks and provenance records."""

    def __init__(self, config: ExtractorConfig | None = None) -> None:
        """Create an extractor with explicit resource limits.

        Args:
            config: Limits and classification settings; defaults are conservative.
        """

        self._config = config or ExtractorConfig()

    def extract(self, path: Path, source: SourceSpec, checksum: Checksum) -> SourceDocument:
        """Extract a PDF without executing document actions or embedded files.

        Args:
            path: Resolved source path already checked against the registry root.
            source: Metadata for the source document.
            checksum: SHA-256 digest calculated before parsing.

        Returns:
            An immutable source document with ordered blocks and page coordinates.

        Raises:
            ExtractionError: For malformed PDFs or configured limit breaches.

        Complexity:
            O(p * (b + t)) for p pages, b blocks, and table-detection work t.
        """

        file_size = path.stat().st_size
        if file_size > self._config.max_file_bytes:
            raise ExtractionError(
                f"source exceeds {self._config.max_file_bytes} byte limit: {source.source_id}"
            )
        try:
            with pymupdf.open(path) as document:  # type: ignore[no-untyped-call]
                if document.page_count == 0:
                    raise ExtractionError(f"source has no pages: {source.source_id}")
                if document.page_count > self._config.max_pages:
                    raise ExtractionError(
                        f"source exceeds {self._config.max_pages} page limit: {source.source_id}"
                    )
                blocks = self._extract_pages(document, source)
                return SourceDocument(
                    source=source,
                    checksum=checksum,
                    page_count=document.page_count,
                    blocks=tuple(blocks),
                )
        except ExtractionError:
            raise
        except (OSError, RuntimeError, ValueError) as error:
            raise ExtractionError(f"unable to parse {source.source_id}: {error}") from error

    def _extract_pages(
        self, document: pymupdf.Document, source: SourceSpec
    ) -> list[ExtractedBlock]:
        """Extract ordered text, tables, and image placeholders from every page.

        Args:
            document: Open PyMuPDF document owned by the caller.
            source: Source metadata used to build stable block IDs.

        Returns:
            Ordered extracted blocks for all pages.

        Raises:
            ExtractionError: If a page exceeds the configured block limit.
        """

        extracted: list[ExtractedBlock] = []
        for page_number in range(document.page_count):
            page_index = page_number + 1
            page: pymupdf.Page = document.load_page(page_number)  # type: ignore[no-untyped-call]
            page_dict = page.get_text("dict", sort=True)  # type: ignore[no-untyped-call]
            raw_blocks = page_dict.get("blocks", [])
            if len(raw_blocks) > self._config.max_blocks_per_page:
                raise ExtractionError(f"page {page_index} exceeds block limit: {source.source_id}")

            tables = list(page.find_tables().tables)  # type: ignore[no-untyped-call]
            table_bboxes = [_as_bbox(table.bbox) for table in tables]
            median_size = _median_font_size(raw_blocks)
            sequence = 0

            for raw_block in raw_blocks:
                bbox = _as_bbox(raw_block.get("bbox", (0, 0, 0, 0)))
                if raw_block.get("type") == 1:
                    sequence += 1
                    extracted.append(
                        ExtractedBlock(
                            block_id=f"{source.source_id}.p{page_index}.b{sequence}",
                            kind=BlockKind.IMAGE,
                            text="Image requires a human-written text alternative.",
                            location=SourceLocation(page=page_index, bbox=bbox),
                            confidence=0.0,
                        )
                    )
                    continue
                if _inside_table(bbox, table_bboxes):
                    continue
                text, font_size = _block_text(raw_block)
                if not text:
                    continue
                kind, level = _classify_text(
                    text, font_size, median_size, self._config.heading_ratio
                )
                sequence += 1
                extracted.append(
                    ExtractedBlock(
                        block_id=f"{source.source_id}.p{page_index}.b{sequence}",
                        kind=kind,
                        text=text,
                        location=SourceLocation(page=page_index, bbox=bbox),
                        heading_level=level,
                        font_size=font_size,
                    )
                )

            for table in tables:
                rows = tuple(tuple((cell or "").strip() for cell in row) for row in table.extract())
                sequence += 1
                extracted.append(
                    ExtractedBlock(
                        block_id=f"{source.source_id}.p{page_index}.b{sequence}",
                        kind=BlockKind.TABLE,
                        text="",
                        location=SourceLocation(
                            page=page_index,
                            bbox=_as_bbox(table.bbox),
                        ),
                        table_rows=rows,
                    )
                )
        return extracted
