"""Typed contracts shared by extraction, normalization, reporting, and publishing.

The models reject unknown fields so source metadata cannot silently drift. Frozen
instances make pipeline stages explicit: each stage returns new validated data.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- variable Identifier: line 37
- variable Checksum: line 38
- variable BoundingBox: line 39
- class FrozenModel: line 42
- class BlockKind: line 48
- class ContentType: line 58
- class IssueSeverity: line 67
- class WarningSeverity: line 75
- class SourceSpec: line 84
- class SourceRegistry: line 130
- class SourceLocation: line 157
- class ExtractedBlock: line 164
- class SourceDocument: line 177
- class WarningNotice: line 186
- class TopicBlock: line 195
- class Topic: line 207
- class MigrationIssue: line 218
- class DocumentMetrics: line 229
- class MigrationReport: line 241
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

Identifier = Annotated[str, Field(pattern=r"^[a-z0-9][a-z0-9._-]{1,63}$")]
Checksum = Annotated[str, Field(pattern=r"^[a-f0-9]{64}$")]
BoundingBox = tuple[float, float, float, float]


class FrozenModel(BaseModel):
    """Reject extra data and prevent mutation after successful validation."""

    model_config = ConfigDict(extra="forbid", frozen=True, str_strip_whitespace=True)


class BlockKind(StrEnum):
    """Kinds of source blocks that the deterministic extractor can emit."""

    HEADING = "heading"
    PARAGRAPH = "paragraph"
    TABLE = "table"
    IMAGE = "image"
    WARNING = "warning"


class ContentType(StrEnum):
    """Supported canonical topic types for the minimum viable pipeline."""

    CONCEPT = "concept"
    TASK = "task"
    REFERENCE = "reference"
    TROUBLESHOOTING = "troubleshooting"


class IssueSeverity(StrEnum):
    """Publication impact assigned to an observable migration issue."""

    INFO = "info"
    WARNING = "warning"
    ERROR = "error"


class WarningSeverity(StrEnum):
    """Safety-notice labels accepted by the canonical content contract."""

    NOTICE = "notice"
    CAUTION = "caution"
    WARNING = "warning"
    DANGER = "danger"


class SourceSpec(FrozenModel):
    """Describe one registered source document and its ownership metadata.

    Attributes:
        source_id: Stable, lowercase identifier used in topic IDs and reports.
        revision: Human-readable source revision.
        product_model: Synthetic product or model scope for the sample corpus.
        owner: Person or team responsible for reviewing the source.
        license: License or usage statement for the source.
        path: Registry-relative path to the source file.
        sha256: Optional expected checksum; a mismatch blocks publication.
        migration_status: Workflow state used by reports and filters.
    """

    source_id: Identifier
    revision: Annotated[str, Field(min_length=1, max_length=80)]
    product_model: Annotated[str, Field(min_length=1, max_length=120)]
    owner: Annotated[str, Field(min_length=1, max_length=120)]
    license: Annotated[str, Field(min_length=1, max_length=120)]
    path: Annotated[str, Field(min_length=1, max_length=260)]
    sha256: Checksum | None = None
    migration_status: Literal["queued", "in-review", "approved"] = "queued"

    @field_validator("path")
    @classmethod
    def path_must_be_relative(cls, value: str) -> str:
        """Reject absolute and parent-traversal paths before filesystem access.

        Args:
            value: Untrusted path string read from the registry.

        Returns:
            The validated relative path.

        Raises:
            ValueError: If the path is absolute or contains a parent segment.
        """

        normalized = value.replace("\\", "/")
        if normalized.startswith("/") or ":" in normalized.split("/", maxsplit=1)[0]:
            raise ValueError("source path must be relative to the registry")
        if ".." in normalized.split("/"):
            raise ValueError("source path cannot traverse outside the registry")
        return normalized


class SourceRegistry(FrozenModel):
    """Validate the versioned list of documents selected for a migration run."""

    registry_version: Literal[1]
    sources: Annotated[list[SourceSpec], Field(min_length=1, max_length=500)]

    @field_validator("sources")
    @classmethod
    def source_ids_must_be_unique(cls, value: list[SourceSpec]) -> list[SourceSpec]:
        """Require unique stable IDs so provenance cannot become ambiguous.

        Args:
            value: Validated source declarations.

        Returns:
            The declarations when every source ID is unique.

        Raises:
            ValueError: If a source ID is repeated.
        """

        identifiers = [source.source_id for source in value]
        if len(identifiers) != len(set(identifiers)):
            raise ValueError("source_id values must be unique")
        return value


class SourceLocation(FrozenModel):
    """Locate a canonical block in its immutable source document."""

    page: Annotated[int, Field(ge=1)]
    bbox: BoundingBox


class ExtractedBlock(FrozenModel):
    """Represent one ordered PDF block before semantic normalization."""

    block_id: Identifier
    kind: BlockKind
    text: str = ""
    location: SourceLocation
    heading_level: Annotated[int, Field(ge=1, le=6)] | None = None
    table_rows: tuple[tuple[str, ...], ...] = ()
    font_size: Annotated[float, Field(ge=0)] = 0.0
    confidence: Annotated[float, Field(ge=0.0, le=1.0)] = 1.0


class SourceDocument(FrozenModel):
    """Collect the deterministic extraction result for one source file."""

    source: SourceSpec
    checksum: Checksum
    page_count: Annotated[int, Field(ge=1)]
    blocks: tuple[ExtractedBlock, ...]


class WarningNotice(FrozenModel):
    """Preserve the four fields required for a publishable safety notice."""

    severity: WarningSeverity
    condition: Annotated[str, Field(min_length=1)]
    consequence: Annotated[str, Field(min_length=1)]
    avoidance: Annotated[str, Field(min_length=1)]


class TopicBlock(FrozenModel):
    """Store normalized content together with its exact source location."""

    kind: BlockKind
    text: str = ""
    provenance: SourceLocation
    source_block_id: Identifier
    heading_level: Annotated[int, Field(ge=1, le=6)] | None = None
    table_rows: tuple[tuple[str, ...], ...] = ()
    warning: WarningNotice | None = None


class Topic(FrozenModel):
    """Represent a reusable canonical topic independent of PDF page layout."""

    topic_id: Identifier
    title: Annotated[str, Field(min_length=1, max_length=160)]
    content_type: ContentType
    source_id: Identifier
    source_revision: Annotated[str, Field(min_length=1, max_length=80)]
    blocks: tuple[TopicBlock, ...]


class MigrationIssue(FrozenModel):
    """Describe a deterministic finding that a reviewer can locate and resolve."""

    code: Identifier
    severity: IssueSeverity
    message: Annotated[str, Field(min_length=1, max_length=500)]
    source_id: Identifier
    page: Annotated[int, Field(ge=1)] | None = None
    block_id: Identifier | None = None


class DocumentMetrics(FrozenModel):
    """Summarize migration coverage for one registered source."""

    source_id: Identifier
    checksum: Checksum
    page_count: Annotated[int, Field(ge=0)]
    block_count: Annotated[int, Field(ge=0)]
    topic_count: Annotated[int, Field(ge=0)]
    table_count: Annotated[int, Field(ge=0)]
    warning_count: Annotated[int, Field(ge=0)]


class MigrationReport(FrozenModel):
    """Provide the machine-readable decision record for one pipeline run."""

    report_version: Literal[1] = 1
    build_id: Identifier
    source_digest: Checksum
    publication_allowed: bool
    source_count: Annotated[int, Field(ge=0)]
    topic_count: Annotated[int, Field(ge=0)]
    issue_counts: dict[IssueSeverity, int]
    documents: tuple[DocumentMetrics, ...]
    issues: tuple[MigrationIssue, ...]
