"""Normalize extracted blocks into stable topics and structured safety notices.

Normalization deliberately uses inspectable rules. It records uncertainty as
issues instead of silently dropping source content or inventing semantics.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- variable WARNING_PART: line 40
- variable WARNING_PREFIX: line 44
- variable SLUG_CHARACTERS: line 45
- class _TopicDraft: line 49
- function slugify: line 56
- function _content_type: line 74
- function _warning_notice: line 97
- function _normalize_block: line 140
- function normalize_document: line 168
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

import re
import unicodedata
from collections import Counter
from dataclasses import dataclass, field

from docfoundry.models import (
    BlockKind,
    ContentType,
    ExtractedBlock,
    IssueSeverity,
    MigrationIssue,
    SourceDocument,
    Topic,
    TopicBlock,
    WarningNotice,
    WarningSeverity,
)

WARNING_PART = re.compile(
    r"(?P<key>condition|consequence|avoidance)\s*=\s*(?P<value>.*?)(?=\s*[;|]\s*(?:condition|consequence|avoidance)\s*=|$)",
    re.IGNORECASE,
)
WARNING_PREFIX = re.compile(r"^(DANGER|WARNING|CAUTION|NOTICE)\s*[:|;-]?\s*", re.IGNORECASE)
SLUG_CHARACTERS = re.compile(r"[^a-z0-9]+")


@dataclass(slots=True)
class _TopicDraft:
    """Collect mutable blocks before constructing an immutable validated topic."""

    title: str
    blocks: list[TopicBlock] = field(default_factory=list)


def slugify(value: str) -> str:
    """Convert Unicode display text into a stable lowercase identifier fragment.

    Args:
        value: Human-readable title or identifier fragment.

    Returns:
        A lowercase ASCII slug, falling back to ``topic`` when empty.

    Complexity:
        O(n) time and space for n Unicode code points.
    """

    normalized = unicodedata.normalize("NFKD", value)
    ascii_value = normalized.encode("ascii", "ignore").decode("ascii").lower()
    return SLUG_CHARACTERS.sub("-", ascii_value).strip("-")[:40] or "topic"


def _content_type(title: str) -> ContentType:
    """Infer a conservative topic type from explicit title terms.

    Args:
        title: Topic heading text.

    Returns:
        The deterministic canonical content type.

    Complexity:
        O(n) time for n title characters.
    """

    lowered = title.casefold()
    if any(word in lowered for word in ("troubleshoot", "diagnostic", "fault")):
        return ContentType.TROUBLESHOOTING
    if any(word in lowered for word in ("install", "configure", "calibrate", "procedure")):
        return ContentType.TASK
    if any(word in lowered for word in ("reference", "specification", "release")):
        return ContentType.REFERENCE
    return ContentType.CONCEPT


def _warning_notice(block: ExtractedBlock) -> tuple[WarningNotice | None, MigrationIssue | None]:
    """Parse a labeled warning without guessing missing safety information.

    Args:
        block: Extracted block whose visible prefix identified a warning.

    Returns:
        A complete warning and no issue, or no warning and a blocking issue.

    Complexity:
        O(n) time and space for n warning characters.
    """

    prefix = WARNING_PREFIX.match(block.text)
    if prefix is None:
        raise ValueError("warning parser received a block without a severity prefix")
    severity = WarningSeverity(prefix.group(1).lower())
    body = block.text[prefix.end() :].strip()
    parts = {
        match.group("key").lower(): match.group("value").strip()
        for match in WARNING_PART.finditer(body)
    }
    missing = sorted({"condition", "consequence", "avoidance"} - parts.keys())
    if missing:
        return None, MigrationIssue(
            code="warning.incomplete",
            severity=IssueSeverity.ERROR,
            message=f"Safety notice is missing required fields: {', '.join(missing)}.",
            source_id=block.block_id.split(".p", maxsplit=1)[0],
            page=block.location.page,
            block_id=block.block_id,
        )
    return (
        WarningNotice(
            severity=severity,
            condition=parts["condition"],
            consequence=parts["consequence"],
            avoidance=parts["avoidance"],
        ),
        None,
    )


def _normalize_block(block: ExtractedBlock) -> tuple[TopicBlock, MigrationIssue | None]:
    """Convert an extracted block while retaining its source coordinates.

    Args:
        block: Validated extraction output.

    Returns:
        Canonical topic block plus an optional migration issue.
    """

    warning: WarningNotice | None = None
    issue: MigrationIssue | None = None
    if block.kind is BlockKind.WARNING:
        warning, issue = _warning_notice(block)
    return (
        TopicBlock(
            kind=block.kind,
            text=block.text,
            provenance=block.location,
            source_block_id=block.block_id,
            heading_level=block.heading_level,
            table_rows=block.table_rows,
            warning=warning,
        ),
        issue,
    )


def normalize_document(
    document: SourceDocument,
) -> tuple[tuple[Topic, ...], tuple[MigrationIssue, ...]]:
    """Segment one extracted source into reusable, provenance-linked topics.

    Args:
        document: Extracted blocks ordered by page and source position.

    Returns:
        Immutable topics and deterministic issues for the source.

    Complexity:
        O(b) expected time and O(b) space for b extracted blocks.
    """

    drafts: list[_TopicDraft] = []
    current = _TopicDraft(title=f"{document.source.product_model} overview")
    issues: list[MigrationIssue] = []
    previous_heading_level = 0

    for extracted in document.blocks:
        normalized, issue = _normalize_block(extracted)
        if issue is not None:
            issues.append(issue)

        if extracted.kind is BlockKind.HEADING and extracted.heading_level is not None:
            if previous_heading_level and extracted.heading_level > previous_heading_level + 1:
                issues.append(
                    MigrationIssue(
                        code="heading.rank-jump",
                        severity=IssueSeverity.WARNING,
                        message=(
                            f"Heading level jumps from {previous_heading_level} "
                            f"to {extracted.heading_level}."
                        ),
                        source_id=document.source.source_id,
                        page=extracted.location.page,
                        block_id=extracted.block_id,
                    )
                )
            previous_heading_level = extracted.heading_level
            if extracted.heading_level <= 2:
                if current.blocks:
                    drafts.append(current)
                current = _TopicDraft(title=extracted.text.replace("\n", " ").strip())
        current.blocks.append(normalized)

    if current.blocks:
        drafts.append(current)
    if not drafts:
        issues.append(
            MigrationIssue(
                code="source.no-content",
                severity=IssueSeverity.ERROR,
                message="No publishable text, table, warning, or image blocks were extracted.",
                source_id=document.source.source_id,
            )
        )
        return (), tuple(issues)

    slug_counts: Counter[str] = Counter()
    topics: list[Topic] = []
    for draft in drafts:
        base_slug = slugify(draft.title)
        slug_counts[base_slug] += 1
        suffix = "" if slug_counts[base_slug] == 1 else f"-{slug_counts[base_slug]}"
        topic_id = f"{document.source.source_id}.{base_slug}{suffix}"
        topics.append(
            Topic(
                topic_id=topic_id,
                title=draft.title,
                content_type=_content_type(draft.title),
                source_id=document.source.source_id,
                source_revision=document.source.revision,
                blocks=tuple(draft.blocks),
            )
        )
    return tuple(topics), tuple(issues)
