"""Orchestrate extraction, normalization, validation, reporting, and publishing.

Every run writes to a temporary sibling directory before an atomic rename.
Blocked runs still retain reports and canonical data for human review.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- class PipelineConfig: line 44
- class PublicationBlocked: line 60
- function _safe_output_directory: line 81
- function _processing_issue: line 101
- function _write_manifest: line 121
- function _commit_staging: line 149
- function run_pipeline: line 178
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from docfoundry.extractor import ExtractionError, ExtractorConfig, PdfExtractor
from docfoundry.models import IssueSeverity, MigrationIssue, MigrationReport, SourceDocument, Topic
from docfoundry.normalizer import normalize_document
from docfoundry.publisher import publish_site
from docfoundry.registry import (
    RegistryError,
    compute_sha256,
    load_registry,
    resolve_source_path,
    verify_checksum,
)
from docfoundry.reporting import build_report, write_canonical_data, write_report
from docfoundry.validator import validate_topics


@dataclass(frozen=True, slots=True)
class PipelineConfig:
    """Define one repeatable pipeline run.

    Attributes:
        registry_path: YAML or JSON registry to process.
        output_directory: Destination for generated artifacts.
        overwrite: Whether an exact existing destination may be replaced.
        extractor: Resource and classification limits for PDF extraction.
    """

    registry_path: Path
    output_directory: Path
    overwrite: bool = False
    extractor: ExtractorConfig = field(default_factory=ExtractorConfig)


class PublicationBlocked(RuntimeError):
    """Signal that reports were written but semantic HTML was not published.

    Attributes:
        report: Deterministic report containing the blocking findings.
        output_directory: Committed directory containing review artifacts.
    """

    def __init__(self, report: MigrationReport, output_directory: Path) -> None:
        """Attach the blocking report and its output location.

        Args:
            report: Report whose error issues prevented publication.
            output_directory: Directory committed for reviewer inspection.
        """

        super().__init__(f"publication blocked; inspect {output_directory / 'reports'}")
        self.report = report
        self.output_directory = output_directory


def _safe_output_directory(output_directory: Path) -> Path:
    """Resolve a destination and reject dangerously broad locations.

    Args:
        output_directory: User-selected build directory.

    Returns:
        Absolute resolved destination.

    Raises:
        ValueError: If the destination is a filesystem root, home, or current directory.
    """

    resolved = output_directory.resolve()
    forbidden = {Path.cwd().resolve(), Path.home().resolve(), Path(resolved.anchor)}
    if resolved in forbidden:
        raise ValueError("output directory must be a dedicated child directory")
    return resolved


def _processing_issue(source_id: str, error: Exception) -> MigrationIssue:
    """Convert a bounded source failure into a deterministic blocking issue.

    Args:
        source_id: Stable registered source identifier.
        error: Registry or extraction error raised for that source.

    Returns:
        Error-severity migration issue safe for report serialization.
    """

    message = " ".join(str(error).split())[:500]
    return MigrationIssue(
        code="source.processing-failed",
        severity=IssueSeverity.ERROR,
        message=message or "Source processing failed without a diagnostic message.",
        source_id=source_id,
    )


def _write_manifest(output_directory: Path) -> None:
    """Write stable SHA-256 hashes for every artifact except the manifest itself.

    Args:
        output_directory: Staging directory containing generated artifacts.

    Complexity:
        O(n) time in total artifact bytes and O(f) memory for f file records.
    """

    records: list[dict[str, str | int]] = []
    for path in sorted(item for item in output_directory.rglob("*") if item.is_file()):
        relative = path.relative_to(output_directory).as_posix()
        if relative == "build-manifest.json":
            continue
        digest = hashlib.sha256()
        with path.open("rb") as artifact:
            for chunk in iter(lambda: artifact.read(1024 * 1024), b""):
                digest.update(chunk)
        records.append(
            {"path": relative, "sha256": digest.hexdigest(), "bytes": path.stat().st_size}
        )
    payload = {"manifest_version": 1, "files": records}
    (output_directory / "build-manifest.json").write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def _commit_staging(staging: Path, destination: Path, overwrite: bool) -> None:
    """Atomically place a completed staging directory at its destination.

    Args:
        staging: Complete temporary build directory.
        destination: Validated exact destination path.
        overwrite: Whether to remove that exact destination first.

    Raises:
        FileExistsError: If the destination exists without explicit overwrite.
        ValueError: If overwrite targets something other than a prior Foundry build.
    """

    if destination.exists():
        if not overwrite:
            raise FileExistsError(f"output already exists: {destination}")
        manifest_path = destination / "build-manifest.json"
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as error:
            raise ValueError(
                "overwrite requires a destination with a valid Foundry build manifest"
            ) from error
        if not isinstance(manifest, dict) or manifest.get("manifest_version") != 1:
            raise ValueError("overwrite requires a version 1 Foundry build manifest")
        shutil.rmtree(destination)
    os.replace(staging, destination)


def run_pipeline(config: PipelineConfig) -> MigrationReport:
    """Run the complete deterministic migration pipeline.

    Args:
        config: Registry, destination, overwrite policy, and extractor limits.

    Returns:
        A publication-allowed migration report.

    Raises:
        PublicationBlocked: After committing review artifacts for blocking issues.
        RegistryError: If the registry document itself cannot be loaded.
        ValueError: If the output destination is unsafe.

    Complexity:
        O(n + b) time for n source bytes and b extracted blocks.
    """

    destination = _safe_output_directory(config.output_directory)
    registry_path = config.registry_path.resolve()
    registry = load_registry(registry_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=f".{destination.name}-", dir=destination.parent))

    documents: list[SourceDocument] = []
    topics: list[Topic] = []
    issues: list[MigrationIssue] = []
    extractor = PdfExtractor(config.extractor)
    try:
        for source in registry.sources:
            try:
                source_path = resolve_source_path(registry_path, source)
                checksum = compute_sha256(source_path)
                verify_checksum(source, checksum)
                document = extractor.extract(source_path, source, checksum)
                source_topics, source_issues = normalize_document(document)
                documents.append(document)
                topics.extend(source_topics)
                issues.extend(source_issues)
            except (ExtractionError, OSError, RegistryError) as error:
                issues.append(_processing_issue(source.source_id, error))

        ordered_topics = tuple(sorted(topics, key=lambda item: item.topic_id))
        issues.extend(validate_topics(ordered_topics))
        report = build_report(tuple(documents), ordered_topics, tuple(issues))
        write_canonical_data(ordered_topics, staging)
        write_report(report, staging)
        if report.publication_allowed:
            publish_site(ordered_topics, report, staging)
        else:
            (staging / "PUBLICATION_BLOCKED.txt").write_text(
                "Publication was blocked by error-severity findings.\n"
                "Review reports/migration-report.md before retrying.\n",
                encoding="utf-8",
            )
        _write_manifest(staging)
        _commit_staging(staging, destination, config.overwrite)
        if not report.publication_allowed:
            raise PublicationBlocked(report, destination)
        return report
    finally:
        if staging.exists():
            shutil.rmtree(staging)
