"""Publish validated canonical topics as an accessible static HTML site.

The renderer escapes source text by default and uses semantic HTML for
headings, safety notices, tables, navigation, and provenance details.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- variable SAFE_FILENAME: line 29
- variable STYLESHEET: line 30
- variable BASE_TEMPLATE: line 48
- variable INDEX_TEMPLATE: line 68
- variable TOPIC_TEMPLATE: line 87
- variable REPORT_TEMPLATE: line 139
- function _environment: line 170
- function topic_filename: line 193
- function publish_site: line 207
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

import re
from pathlib import Path

from jinja2 import DictLoader, Environment, StrictUndefined, select_autoescape

from docfoundry.models import BlockKind, MigrationReport, Topic

SAFE_FILENAME = re.compile(r"[^a-z0-9-]+")
STYLESHEET = """\
:root { color-scheme: light; font-family: system-ui, sans-serif; line-height: 1.6; }
body { margin: 0 auto; max-width: 72rem; padding: 1.5rem; color: #18212b; }
a { color: #075ea8; }
a:focus-visible { outline: 3px solid #f0a202; outline-offset: 3px; }
header, footer { border-block: 1px solid #cbd5df; padding-block: 1rem; }
nav ul { display: flex; flex-wrap: wrap; gap: .75rem 1.5rem; padding-left: 1.25rem; }
.metadata { background: #f3f6f9; padding: .75rem 1rem; }
.warning { border: 3px solid #a33; padding: 1rem; margin-block: 1rem; }
.warning h3 { margin-top: 0; }
table { border-collapse: collapse; width: 100%; margin-block: 1rem; }
th, td { border: 1px solid #657786; padding: .5rem; text-align: left; vertical-align: top; }
th { background: #e7edf3; }
.provenance { color: #455565; font-size: .9rem; }
.status { border-left: .35rem solid #c77b00; background: #fff6df; padding: .75rem; }
code { overflow-wrap: anywhere; }
"""

BASE_TEMPLATE = """\
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ page_title }}</title>
  <link rel="stylesheet" href="{{ root_prefix }}assets/site.css">
</head>
<body>
  <header>
    <a href="{{ root_prefix }}index.html">Engineering Documentation Foundry</a>
    <p>Deterministic technical-document migration output.</p>
  </header>
  <main id="main-content">{% block content %}{% endblock %}</main>
  <footer><p>Generated from versioned synthetic sources with block-level provenance.</p></footer>
</body>
</html>
"""

INDEX_TEMPLATE = """\
{% extends "base.html" %}
{% block content %}
<h1>Migration build {{ report.build_id }}</h1>
<dl class="metadata">
  <dt>Source digest</dt><dd><code>{{ report.source_digest }}</code></dd>
  <dt>Sources</dt><dd>{{ report.source_count }}</dd>
  <dt>Topics</dt><dd>{{ report.topic_count }}</dd>
</dl>
<h2>Canonical topics</h2>
<nav aria-label="Canonical topics"><ul>
{% for item in topic_links %}
  <li><a href="topics/{{ item.filename }}">{{ item.topic.title }}</a></li>
{% endfor %}
</ul></nav>
<p><a href="reports/migration-report.html">View migration quality report</a></p>
{% endblock %}
"""

TOPIC_TEMPLATE = """\
{% extends "base.html" %}
{% block content %}
<p><a href="../index.html">Back to topic index</a></p>
<h1>{{ topic.title }}</h1>
<dl class="metadata">
  <dt>Topic ID</dt><dd><code>{{ topic.topic_id }}</code></dd>
  <dt>Content type</dt><dd>{{ topic.content_type.value }}</dd>
  <dt>Source</dt><dd><code>{{ topic.source_id }}</code>, revision {{ topic.source_revision }}</dd>
</dl>
{% for block in topic.blocks %}
  {% if block.kind.value == "heading" %}
    {% if block.heading_level and block.heading_level <= 2 %}
      <h2>{{ block.text }}</h2>
    {% else %}
      <h3>{{ block.text }}</h3>
    {% endif %}
  {% elif block.kind.value == "paragraph" %}
    <p>{{ block.text }}</p>
  {% elif block.kind.value == "warning" and block.warning %}
    <aside class="warning" aria-label="{{ block.warning.severity.value }} safety notice">
      <h3>{{ block.warning.severity.value|upper }}</h3>
      <p><strong>Condition:</strong> {{ block.warning.condition }}</p>
      <p><strong>Consequence:</strong> {{ block.warning.consequence }}</p>
      <p><strong>Avoidance:</strong> {{ block.warning.avoidance }}</p>
    </aside>
  {% elif block.kind.value == "warning" %}
    <p class="status">Unresolved safety notice: {{ block.text }}</p>
  {% elif block.kind.value == "table" %}
    <table>
      <caption>Data from {{ topic.title }}</caption>
      <thead><tr>
      {% for cell in block.table_rows[0] %}<th scope="col">{{ cell }}</th>{% endfor %}
      </tr></thead>
      <tbody>
      {% for row in block.table_rows[1:] %}
        <tr>{% for cell in row %}<td>{{ cell }}</td>{% endfor %}</tr>
      {% endfor %}
      </tbody>
    </table>
  {% elif block.kind.value == "image" %}
    <section class="status" aria-label="Image review required">
      <strong>Image review required.</strong> {{ block.text }}
    </section>
  {% endif %}
  <p class="provenance">
    Source page {{ block.provenance.page }}, block <code>{{ block.source_block_id }}</code>
  </p>
{% endfor %}
{% endblock %}
"""

REPORT_TEMPLATE = """\
{% extends "base.html" %}
{% block content %}
<h1>Migration quality report</h1>
<p>
  Build <code>{{ report.build_id }}</code>; publication allowed:
  <strong>{{ "yes" if report.publication_allowed else "no" }}</strong>.
</p>
<h2>Issue counts</h2>
<ul>
{% for severity, count in report.issue_counts.items() %}
  <li>{{ severity.value }}: {{ count }}</li>
{% endfor %}
</ul>
<h2>Findings</h2>
{% if report.issues %}
<ul>
{% for issue in report.issues %}
  <li>
    <strong>{{ issue.severity.value }} {{ issue.code }}</strong>: {{ issue.source_id }}
    {% if issue.page %}, page {{ issue.page }}{% endif %}: {{ issue.message }}
  </li>
{% endfor %}
</ul>
{% else %}
<p>No automated findings.</p>
{% endif %}
{% endblock %}
"""


def _environment() -> Environment:
    """Create the locked-down in-memory Jinja environment.

    Returns:
        An environment with HTML autoescaping and strict undefined values.
    """

    return Environment(
        loader=DictLoader(
            {
                "base.html": BASE_TEMPLATE,
                "index.html": INDEX_TEMPLATE,
                "topic.html": TOPIC_TEMPLATE,
                "report.html": REPORT_TEMPLATE,
            }
        ),
        autoescape=select_autoescape(("html", "xml"), default=True),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
    )


def topic_filename(topic: Topic) -> str:
    """Return a portable filename for a validated topic ID.

    Args:
        topic: Canonical topic whose identifier provides the stable filename.

    Returns:
        A lowercase HTML filename containing only letters, digits, and hyphens.
    """

    safe_stem = SAFE_FILENAME.sub("-", topic.topic_id.lower()).strip("-")
    return f"{safe_stem}.html"


def publish_site(
    topics: tuple[Topic, ...], report: MigrationReport, output_directory: Path
) -> None:
    """Render the site and an HTML view of the quality report.

    Args:
        topics: Validated canonical topics in deterministic order.
        report: Publication decision and migration findings.
        output_directory: Existing staging directory for all artifacts.

    Raises:
        ValueError: If called for a blocked report.

    Complexity:
        O(b) time and output space for b canonical blocks.
    """

    if not report.publication_allowed:
        raise ValueError("cannot publish a site for a blocked migration report")

    environment = _environment()
    site_directory = output_directory / "site"
    topic_directory = site_directory / "topics"
    assets_directory = site_directory / "assets"
    report_directory = output_directory / "reports"
    topic_directory.mkdir(parents=True, exist_ok=True)
    assets_directory.mkdir(parents=True, exist_ok=True)
    report_directory.mkdir(parents=True, exist_ok=True)
    (assets_directory / "site.css").write_text(STYLESHEET, encoding="utf-8")

    ordered_topics = tuple(sorted(topics, key=lambda item: item.topic_id))
    topic_links = tuple(
        {"topic": topic, "filename": topic_filename(topic)} for topic in ordered_topics
    )
    index_html = environment.get_template("index.html").render(
        page_title="Engineering Documentation Foundry",
        root_prefix="",
        report=report,
        topic_links=topic_links,
    )
    (site_directory / "index.html").write_text(index_html + "\n", encoding="utf-8")

    topic_template = environment.get_template("topic.html")
    for topic in ordered_topics:
        html = topic_template.render(
            page_title=topic.title,
            root_prefix="../",
            topic=topic,
            BlockKind=BlockKind,
        )
        (topic_directory / topic_filename(topic)).write_text(html + "\n", encoding="utf-8")

    external_report_html = environment.get_template("report.html").render(
        page_title="Migration quality report", root_prefix="../site/", report=report
    )
    (report_directory / "migration-report.html").write_text(
        external_report_html + "\n", encoding="utf-8"
    )
    site_report_directory = site_directory / "reports"
    site_report_directory.mkdir(parents=True, exist_ok=True)
    site_report_html = environment.get_template("report.html").render(
        page_title="Migration quality report", root_prefix="../", report=report
    )
    (site_report_directory / "migration-report.html").write_text(
        site_report_html + "\n", encoding="utf-8"
    )
