"""Load source registries and enforce path and checksum boundaries.

Filesystem resolution happens in this module so extractors never receive an
unchecked path from YAML or JSON input.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- class RegistryError: line 28
- function load_registry: line 32
- function resolve_source_path: line 64
- function compute_sha256: line 92
- function verify_checksum: line 119
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import yaml

from docfoundry.models import Checksum, SourceRegistry, SourceSpec


class RegistryError(ValueError):
    """Report invalid registry syntax, paths, source types, or checksums."""


def load_registry(registry_path: Path) -> SourceRegistry:
    """Parse and validate one YAML or JSON registry.

    Args:
        registry_path: Path to the registry file supplied to the CLI.

    Returns:
        A validated immutable source registry.

    Raises:
        RegistryError: If syntax, extension, or model validation fails.

    Complexity:
        O(n) time and space in the size of the registry document.
    """

    suffix = registry_path.suffix.lower()
    try:
        raw_text = registry_path.read_text(encoding="utf-8")
        if suffix == ".json":
            payload: Any = json.loads(raw_text)
        elif suffix in {".yaml", ".yml"}:
            payload = yaml.safe_load(raw_text)
        else:
            raise RegistryError("registry must use .json, .yaml, or .yml")
        return SourceRegistry.model_validate(payload)
    except (OSError, json.JSONDecodeError, yaml.YAMLError, ValueError) as error:
        if isinstance(error, RegistryError):
            raise
        raise RegistryError(f"unable to load registry: {error}") from error


def resolve_source_path(registry_path: Path, source: SourceSpec) -> Path:
    """Resolve a registered source and reject symlink or traversal escapes.

    Args:
        registry_path: Registry whose parent directory defines the trust root.
        source: Validated relative source declaration.

    Returns:
        The resolved source path within the registry directory.

    Raises:
        RegistryError: If the resolved path escapes the trust root or is absent.

    Complexity:
        O(k) time for filesystem path resolution, where k is path depth.
    """

    root = registry_path.resolve().parent
    candidate = (root / source.path).resolve()
    if not candidate.is_relative_to(root):
        raise RegistryError(f"source escapes registry directory: {source.source_id}")
    if not candidate.is_file():
        raise RegistryError(f"source file does not exist: {source.source_id}")
    if candidate.suffix.lower() != ".pdf":
        raise RegistryError(f"unsupported source type for {source.source_id}: {candidate.suffix}")
    return candidate


def compute_sha256(path: Path, chunk_size: int = 1024 * 1024) -> Checksum:
    """Hash a file with bounded memory.

    Args:
        path: Existing file to hash.
        chunk_size: Maximum bytes read in one iteration.

    Returns:
        Lowercase SHA-256 hexadecimal digest.

    Raises:
        ValueError: If chunk_size is not positive.
        OSError: If the file cannot be read.

    Complexity:
        O(n) time and O(chunk_size) memory for an n-byte file.
    """

    if chunk_size <= 0:
        raise ValueError("chunk_size must be positive")
    digest = hashlib.sha256()
    with path.open("rb") as source_file:
        for chunk in iter(lambda: source_file.read(chunk_size), b""):
            digest.update(chunk)
    return digest.hexdigest()


def verify_checksum(source: SourceSpec, actual: Checksum) -> None:
    """Block processing when a declared source checksum does not match.

    Args:
        source: Source metadata with an optional expected checksum.
        actual: Checksum calculated from the current file.

    Raises:
        RegistryError: If an expected checksum is present and mismatched.
    """

    if source.sha256 is not None and source.sha256 != actual:
        raise RegistryError(
            f"checksum mismatch for {source.source_id}: expected {source.sha256}, got {actual}"
        )
