"""Build deterministic migration reports and source-to-topic trace records.

Reports intentionally omit wall-clock timestamps so identical source bytes and
configuration produce byte-for-byte identical generated artifacts.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- function build_report: line 33
- function write_report: line 95
- function write_canonical_data: line 150
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

import hashlib
import json
from collections import Counter
from pathlib import Path

from docfoundry.models import (
    BlockKind,
    DocumentMetrics,
    IssueSeverity,
    MigrationIssue,
    MigrationReport,
    SourceDocument,
    Topic,
)
from docfoundry.validator import publication_is_allowed


def build_report(
    documents: tuple[SourceDocument, ...],
    topics: tuple[Topic, ...],
    issues: tuple[MigrationIssue, ...],
) -> MigrationReport:
    """Aggregate per-source coverage and stable build identity.

    Args:
        documents: Successfully extracted sources.
        topics: Canonical topics from those sources.
        issues: All detected migration findings.

    Returns:
        A deterministic machine-readable report.

    Complexity:
        O(d + t + i + b) time and O(d + i) space.
    """

    digest = hashlib.sha256()
    for document in sorted(documents, key=lambda item: item.source.source_id):
        digest.update(document.source.source_id.encode("utf-8"))
        digest.update(document.checksum.encode("ascii"))
    source_digest = digest.hexdigest()
    issue_counts = Counter(issue.severity for issue in issues)
    topics_per_source = Counter(topic.source_id for topic in topics)
    document_metrics = tuple(
        DocumentMetrics(
            source_id=document.source.source_id,
            checksum=document.checksum,
            page_count=document.page_count,
            block_count=len(document.blocks),
            topic_count=topics_per_source[document.source.source_id],
            table_count=sum(block.kind is BlockKind.TABLE for block in document.blocks),
            warning_count=sum(block.kind is BlockKind.WARNING for block in document.blocks),
        )
        for document in sorted(documents, key=lambda item: item.source.source_id)
    )
    sorted_issues = tuple(
        sorted(
            issues,
            key=lambda item: (
                item.severity.value,
                item.source_id,
                item.page or 0,
                item.code,
                item.message,
            ),
        )
    )
    return MigrationReport(
        build_id=f"build-{source_digest[:12]}",
        source_digest=source_digest,
        publication_allowed=publication_is_allowed(sorted_issues),
        source_count=len(documents),
        topic_count=len(topics),
        issue_counts={severity: issue_counts[severity] for severity in IssueSeverity},
        documents=document_metrics,
        issues=sorted_issues,
    )


def write_report(report: MigrationReport, output_directory: Path) -> None:
    """Write JSON and Markdown report views with identical facts.

    Args:
        report: Validated migration report.
        output_directory: Existing staging directory for report artifacts.
    """

    reports = output_directory / "reports"
    reports.mkdir(parents=True, exist_ok=True)
    payload = report.model_dump(mode="json")
    (reports / "migration-report.json").write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    lines = [
        "# Migration quality report",
        "",
        f"Build ID: `{report.build_id}`",
        f"Publication allowed: **{'yes' if report.publication_allowed else 'no'}**",
        f"Sources: {report.source_count}",
        f"Topics: {report.topic_count}",
        "",
        "## Issue counts",
        "",
    ]
    lines.extend(
        f"- {severity.value}: {report.issue_counts[severity]}" for severity in IssueSeverity
    )
    lines.extend(
        [
            "",
            "## Source coverage",
            "",
            "| Source | Pages | Blocks | Topics | Tables | Warnings |",
            "|---|---:|---:|---:|---:|---:|",
        ]
    )
    lines.extend(
        f"| {item.source_id} | {item.page_count} | {item.block_count} | "
        f"{item.topic_count} | {item.table_count} | {item.warning_count} |"
        for item in report.documents
    )
    lines.extend(["", "## Findings", ""])
    if report.issues:
        lines.extend(
            f"- **{issue.severity.value} `{issue.code}`** - {issue.source_id}"
            f"{f' page {issue.page}' if issue.page else ''}: {issue.message}"
            for issue in report.issues
        )
    else:
        lines.append("No automated findings.")
    (reports / "migration-report.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_canonical_data(topics: tuple[Topic, ...], output_directory: Path) -> None:
    """Write canonical topic JSON and a JSON Lines provenance trace.

    Args:
        topics: Validated canonical topics.
        output_directory: Existing staging directory for generated artifacts.

    Complexity:
        O(b) time and output space for b canonical blocks.
    """

    canonical = output_directory / "canonical"
    canonical.mkdir(parents=True, exist_ok=True)
    topic_payload = [topic.model_dump(mode="json") for topic in topics]
    (canonical / "topics.json").write_text(
        json.dumps(topic_payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    with (canonical / "trace.jsonl").open("w", encoding="utf-8", newline="\n") as trace_file:
        for topic in topics:
            for block_index, block in enumerate(topic.blocks, start=1):
                record = {
                    "topic_id": topic.topic_id,
                    "block_index": block_index,
                    "source_id": topic.source_id,
                    "source_revision": topic.source_revision,
                    "source_block_id": block.source_block_id,
                    "page": block.provenance.page,
                    "bbox": block.provenance.bbox,
                }
                trace_file.write(json.dumps(record, sort_keys=True) + "\n")
