"""Validate canonical topics before the publisher can create a web site.

The rules focus on semantic loss that automation can detect reliably. Human
technical review remains required for engineering meaning and image descriptions.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- function validate_topics: line 20
- function publication_is_allowed: line 98
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

from collections import Counter

from docfoundry.models import BlockKind, IssueSeverity, MigrationIssue, Topic


def validate_topics(topics: tuple[Topic, ...]) -> tuple[MigrationIssue, ...]:
    """Run deterministic semantic and accessibility checks over topics.

    Args:
        topics: Canonical topics from all successfully extracted sources.

    Returns:
        Issues sorted later by the reporting stage.

    Complexity:
        O(b + r*c) time for b blocks and r-by-c table cells; O(t) memory for t IDs.
    """

    issues: list[MigrationIssue] = []
    topic_counts = Counter(topic.topic_id for topic in topics)
    for topic_id, count in topic_counts.items():
        if count > 1:
            source_id = next(topic.source_id for topic in topics if topic.topic_id == topic_id)
            issues.append(
                MigrationIssue(
                    code="topic.duplicate-id",
                    severity=IssueSeverity.ERROR,
                    message=f"Topic ID appears {count} times: {topic_id}.",
                    source_id=source_id,
                )
            )

    for topic in topics:
        if not topic.blocks:
            issues.append(
                MigrationIssue(
                    code="topic.empty",
                    severity=IssueSeverity.ERROR,
                    message=f"Topic has no content blocks: {topic.topic_id}.",
                    source_id=topic.source_id,
                )
            )
        for block in topic.blocks:
            if block.kind is BlockKind.IMAGE:
                issues.append(
                    MigrationIssue(
                        code="image.alt-required",
                        severity=IssueSeverity.WARNING,
                        message="Image requires human review and a meaningful text alternative.",
                        source_id=topic.source_id,
                        page=block.provenance.page,
                        block_id=block.source_block_id,
                    )
                )
            if block.kind is BlockKind.WARNING and block.warning is None:
                continue
            if block.kind is BlockKind.TABLE:
                if not block.table_rows or not any(cell for cell in block.table_rows[0]):
                    issues.append(
                        MigrationIssue(
                            code="table.header-missing",
                            severity=IssueSeverity.ERROR,
                            message="Detected table has no non-empty header row.",
                            source_id=topic.source_id,
                            page=block.provenance.page,
                            block_id=block.source_block_id,
                        )
                    )
                row_widths = {len(row) for row in block.table_rows}
                if len(row_widths) > 1:
                    issues.append(
                        MigrationIssue(
                            code="table.irregular",
                            severity=IssueSeverity.WARNING,
                            message="Detected table rows have different column counts.",
                            source_id=topic.source_id,
                            page=block.provenance.page,
                            block_id=block.source_block_id,
                        )
                    )
    return tuple(issues)


def publication_is_allowed(issues: tuple[MigrationIssue, ...]) -> bool:
    """Return true only when no issue has blocking error severity.

    Args:
        issues: Combined extraction, normalization, and validation findings.

    Returns:
        True when a semantic HTML site may be produced.

    Complexity:
        O(i) worst-case time and O(1) extra memory for i issues.
    """

    return all(issue.severity is not IssueSeverity.ERROR for issue in issues)
