"""Export JSON Schema files for the public registry and report contracts.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- variable ROOT: line 18
- variable SCHEMA_DIRECTORY: line 19
- function main: line 22
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

import json
from pathlib import Path

from docfoundry.models import MigrationReport, SourceRegistry

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIRECTORY = ROOT / "schemas"


def main() -> None:
    """Write stable, human-readable JSON Schema documents."""

    SCHEMA_DIRECTORY.mkdir(parents=True, exist_ok=True)
    schemas = {
        "source-registry.schema.json": SourceRegistry.model_json_schema(),
        "migration-report.schema.json": MigrationReport.model_json_schema(),
    }
    for filename, schema in schemas.items():
        (SCHEMA_DIRECTORY / filename).write_text(
            json.dumps(schema, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )


if __name__ == "__main__":
    main()
