"""Generate the original synthetic PDF corpus used by examples and tests.

The documents use invented products and deliberately exercise headings, prose,
procedures, structured safety notices, and ruled tables without third-party data.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- variable ROOT: line 37
- variable SOURCE_DIRECTORY: line 38
- class FixtureSpec: line 42
- variable FIXTURES: line 68
- function _styles: line 239
- function build_fixture: line 267
- function main: line 324
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIRECTORY = ROOT / "examples" / "sources"


@dataclass(frozen=True, slots=True)
class FixtureSpec:
    """Describe one synthetic technical manual.

    Attributes:
        filename: Portable PDF filename.
        title: Visible document title.
        model: Invented product identifier.
        section: Main procedural or reference heading.
        paragraphs: Explanatory source paragraphs.
        steps: Ordered task steps.
        table_headers: Header cells for a ruled data table.
        table_rows: Body cells for the table.
        warning: Structured notice using the pipeline warning grammar.
    """

    filename: str
    title: str
    model: str
    section: str
    paragraphs: tuple[str, ...]
    steps: tuple[str, ...]
    table_headers: tuple[str, ...]
    table_rows: tuple[tuple[str, ...], ...]
    warning: str


FIXTURES = (
    FixtureSpec(
        filename="pump-controller-guide.pdf",
        title="Pump Controller Guide",
        model="Aquila PX-4",
        section="Commissioning procedure",
        paragraphs=(
            "The Aquila PX-4 coordinates a variable-speed pump with dry-run protection.",
            "Record the verified motor rating and installation identifier before commissioning.",
        ),
        steps=("Isolate incoming power.", "Verify terminal torque.", "Run the low-speed test."),
        table_headers=("Parameter", "Default", "Allowed range"),
        table_rows=(("Ramp time", "8 s", "2-60 s"), ("Stop delay", "3 s", "0-20 s")),
        warning=(
            "WARNING: condition=power is connected; consequence=electric shock; "
            "avoidance=isolate power"
        ),
    ),
    FixtureSpec(
        filename="sensor-calibration.pdf",
        title="Pressure Sensor Calibration",
        model="Nimbus PS-8",
        section="Calibration task",
        paragraphs=(
            "The Nimbus PS-8 converts a sealed pressure input into a four-to-twenty "
            "milliamp signal.",
            "Use a traceable reference and retain both as-found and as-left readings.",
        ),
        steps=("Vent the process port.", "Apply the zero reference.", "Verify three span points."),
        table_headers=("Reference", "Expected", "Tolerance"),
        table_rows=(
            ("0 percent", "4.00 mA", "+/-0.04 mA"),
            ("100 percent", "20.00 mA", "+/-0.04 mA"),
        ),
        warning=(
            "CAUTION: condition=port is pressurized; consequence=fluid release; "
            "avoidance=vent the port"
        ),
    ),
    FixtureSpec(
        filename="firmware-release-notes.pdf",
        title="Firmware Release Notes",
        model="Forge RT-12",
        section="Upgrade procedure",
        paragraphs=(
            "Release 3.2 adds bounded reconnect backoff and diagnostics for interrupted updates.",
            "The signed image is compatible with hardware revisions B and C.",
        ),
        steps=(
            "Export the configuration.",
            "Verify the image digest.",
            "Apply the image and restart.",
        ),
        table_headers=("Change", "Impact", "Action"),
        table_rows=(
            ("Reconnect backoff", "Lower network load", "None"),
            ("Image format", "Signed only", "Verify digest"),
        ),
        warning=(
            "NOTICE: condition=upgrade starts; consequence=brief outage; "
            "avoidance=schedule maintenance"
        ),
    ),
    FixtureSpec(
        filename="network-troubleshooting.pdf",
        title="Network Troubleshooting Handbook",
        model="Relay NX-6",
        section="Connection troubleshooting",
        paragraphs=(
            "The Relay NX-6 exposes a diagnostic status page on the isolated service network.",
            "Test physical link state before changing addressing or transport settings.",
        ),
        steps=(
            "Inspect link indicators.",
            "Ping the configured gateway.",
            "Review bounded retry logs.",
        ),
        table_headers=("Symptom", "Likely cause", "Check"),
        table_rows=(
            ("No link", "Cable fault", "Continuity"),
            ("Timeout", "Route missing", "Gateway"),
        ),
        warning=(
            "CAUTION: condition=settings are changed; consequence=lost access; "
            "avoidance=export configuration"
        ),
    ),
    FixtureSpec(
        filename="api-reference.pdf",
        title="Telemetry API Reference",
        model="Atlas API-2",
        section="Endpoint reference",
        paragraphs=(
            "The Atlas API-2 accepts versioned JSON requests over authenticated HTTPS.",
            "Clients must use idempotency keys for commands that can be retried.",
        ),
        steps=("Obtain a scoped token.", "Send a version header.", "Handle rate-limit responses."),
        table_headers=("Method", "Path", "Result"),
        table_rows=(
            ("GET", "/v1/status", "Current state"),
            ("POST", "/v1/commands", "Accepted command"),
        ),
        warning=(
            "NOTICE: condition=token is shared; consequence=unauthorized access; "
            "avoidance=store tokens securely"
        ),
    ),
    FixtureSpec(
        filename="installation-procedure.pdf",
        title="Remote I/O Installation Procedure",
        model="Harbor IO-16",
        section="Installation task",
        paragraphs=(
            "The Harbor IO-16 mounts on a grounded DIN rail inside a rated enclosure.",
            "Keep signal wiring separated from switching conductors throughout the cabinet.",
        ),
        steps=("Lock out cabinet power.", "Mount the coupler.", "Land and label field wiring."),
        table_headers=("Item", "Requirement", "Verification"),
        table_rows=(
            ("DIN rail", "Grounded", "Continuity test"),
            ("Clearance", "25 mm", "Visual check"),
        ),
        warning=(
            "DANGER: condition=cabinet is energized; consequence=fatal shock; "
            "avoidance=apply lockout"
        ),
    ),
    FixtureSpec(
        filename="maintenance-checklist.pdf",
        title="Preventive Maintenance Checklist",
        model="Summit Drive-9",
        section="Quarterly maintenance task",
        paragraphs=(
            "The Summit Drive-9 records fan runtime and thermal margin for planned maintenance.",
            "Complete the checklist without bypassing interlocks or removing protective earth.",
        ),
        steps=("Review the event history.", "Inspect airflow paths.", "Confirm enclosure seals."),
        table_headers=("Check", "Acceptance", "Record"),
        table_rows=(
            ("Fan runtime", "Below 20,000 h", "Hours"),
            ("Heat sink", "No obstruction", "Pass/fail"),
        ),
        warning=(
            "WARNING: condition=guards are removed; consequence=moving-part injury; "
            "avoidance=stop the drive"
        ),
    ),
    FixtureSpec(
        filename="safety-and-specifications.pdf",
        title="Safety and Specifications",
        model="Cobalt PSU-24",
        section="Electrical specifications",
        paragraphs=(
            "The Cobalt PSU-24 supplies regulated direct current to protected control circuits.",
            "Derate output current for high ambient temperature and restricted ventilation.",
        ),
        steps=(
            "Verify branch protection.",
            "Connect protective earth.",
            "Measure unloaded output.",
        ),
        table_headers=("Rating", "Minimum", "Maximum"),
        table_rows=(("Input", "100 VAC", "240 VAC"), ("Output", "23.5 VDC", "24.5 VDC")),
        warning=(
            "DANGER: condition=input terminals are exposed; consequence=fatal shock; "
            "avoidance=fit the cover"
        ),
    ),
)


def _styles() -> dict[str, ParagraphStyle]:
    """Create predictable styles with clearly separated heading sizes.

    Returns:
        Named ReportLab paragraph styles used by every fixture.
    """

    sample = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "FixtureTitle", parent=sample["Title"], fontSize=22, leading=26, alignment=TA_CENTER
        ),
        "heading": ParagraphStyle(
            "FixtureHeading", parent=sample["Heading2"], fontSize=16, leading=19, spaceBefore=12
        ),
        "body": ParagraphStyle(
            "FixtureBody", parent=sample["BodyText"], fontSize=10, leading=14, spaceAfter=8
        ),
        "warning": ParagraphStyle(
            "FixtureWarning",
            parent=sample["BodyText"],
            fontSize=7.5,
            leading=10,
            textColor=colors.darkred,
        ),
    }


def build_fixture(spec: FixtureSpec, destination: Path) -> None:
    """Render one deterministic, two-page synthetic technical PDF.

    Args:
        spec: Original text and table data for the fixture.
        destination: PDF path to create.
    """

    styles = _styles()
    document = SimpleDocTemplate(
        str(destination),
        pagesize=LETTER,
        rightMargin=0.7 * inch,
        leftMargin=0.7 * inch,
        topMargin=0.7 * inch,
        bottomMargin=0.7 * inch,
        title=spec.title,
        author="Jason Stys",
        subject="Synthetic technical-document migration fixture",
    )
    story: list[object] = [
        Paragraph(spec.title, styles["title"]),
        Paragraph(f"Model {spec.model} | Revision 1.0", styles["body"]),
        Spacer(1, 0.1 * inch),
        Paragraph("Overview", styles["heading"]),
    ]
    story.extend(Paragraph(paragraph, styles["body"]) for paragraph in spec.paragraphs)
    story.extend(
        [
            Paragraph(spec.warning, styles["warning"]),
            PageBreak(),
            Paragraph(spec.section, styles["heading"]),
        ]
    )
    story.extend(
        Paragraph(f"{index}. {step}", styles["body"])
        for index, step in enumerate(spec.steps, start=1)
    )
    table_data = [list(spec.table_headers), *(list(row) for row in spec.table_rows)]
    table = Table(table_data, repeatRows=1, hAlign="LEFT")
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#D9E7F2")),
                ("GRID", (0, 0), (-1, -1), 0.75, colors.black),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.extend([Spacer(1, 0.15 * inch), table])
    document.build(story)


def main() -> None:
    """Generate every fixture under ``examples/sources``."""

    SOURCE_DIRECTORY.mkdir(parents=True, exist_ok=True)
    for fixture in FIXTURES:
        build_fixture(fixture, SOURCE_DIRECTORY / fixture.filename)


if __name__ == "__main__":
    main()
