"""Update line-accurate symbol indexes in every repository Python file.

The generated module-header section lists top-level variables, functions, and
classes. Repeated passes converge after line numbers shift during replacement.

Symbol index (generated by tools/update_symbol_index.py):
@@SYMBOL_INDEX_START
- variable ROOT: line 23
- variable START: line 24
- variable END: line 25
- function _symbol_rows: line 28
- function _update_file: line 52
- function _python_files: line 86
- function main: line 97
@@SYMBOL_INDEX_END
"""

from __future__ import annotations

import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
START = "@@SYMBOL_INDEX_START"
END = "@@SYMBOL_INDEX_END"


def _symbol_rows(tree: ast.Module) -> list[str]:
    """Collect line-numbered top-level symbols from a parsed module.

    Args:
        tree: Abstract syntax tree for one Python module.

    Returns:
        Human-readable rows in source order.
    """

    rows: list[str] = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            rows.append(f"function {node.name}: line {node.lineno}")
        elif isinstance(node, ast.ClassDef):
            rows.append(f"class {node.name}: line {node.lineno}")
        elif isinstance(node, ast.Assign):
            names = [target.id for target in node.targets if isinstance(target, ast.Name)]
            rows.extend(f"variable {name}: line {node.lineno}" for name in names)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            rows.append(f"variable {node.target.id}: line {node.lineno}")
    return rows


def _update_file(path: Path) -> bool:
    """Replace one module's generated index when its rows have changed.

    Args:
        path: Python source file containing both marker lines.

    Returns:
        True when the file was rewritten.

    Raises:
        ValueError: If only one marker exists or their order is invalid.
    """

    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    marker_count = sum(line.strip() in {START, END} for line in lines)
    if marker_count == 0:
        raise ValueError(f"missing symbol-index markers: {path.relative_to(ROOT)}")
    if marker_count != 2:
        raise ValueError(f"invalid symbol-index markers: {path.relative_to(ROOT)}")
    start = next(index for index, line in enumerate(lines) if line.strip() == START)
    end = next(index for index, line in enumerate(lines) if line.strip() == END)
    if end <= start:
        raise ValueError(f"reversed symbol-index markers: {path.relative_to(ROOT)}")
    rows = _symbol_rows(ast.parse(text, filename=str(path)))
    replacement = [f"- {row}" for row in rows] or ["- no top-level symbols"]
    updated = [*lines[: start + 1], *replacement, *lines[end:]]
    updated_text = "\n".join(updated) + "\n"
    if updated_text == text:
        return False
    path.write_text(updated_text, encoding="utf-8", newline="\n")
    return True


def _python_files() -> tuple[Path, ...]:
    """Return tracked source, test, and tool Python paths in stable order.

    Returns:
        Sorted Python paths under the repository's code directories.
    """

    roots = (ROOT / "src", ROOT / "tests", ROOT / "tools")
    return tuple(sorted(path for root in roots if root.exists() for path in root.rglob("*.py")))


def main() -> None:
    """Rewrite symbol indexes until all embedded line numbers reach a fixed point."""

    paths = _python_files()
    for _pass_number in range(8):
        changed = sum(_update_file(path) for path in paths)
        if changed == 0:
            return
    raise RuntimeError("symbol indexes did not converge after eight passes")


if __name__ == "__main__":
    main()
